### ISSUE TITLE
Add validate_assignment to HealthVariable

### ISSUE THREAD

**Issue by victorventuri** [ROVI-org/auto-soh#12]
Seeing as `HealthVariable`s will be updated all the time, I think it would be wise to add a `validate_assignment=True` in their definition to make sure we don't accidentally attribute something incorrect post-instantiation.

**Comment by victorventuri** [comment]
Already discussed this, and the `validate_assignment` flag brings too much of an overhead for online estimation. @WardLT should we close this?

**Comment by WardLT** [comment]
I think so
