### ISSUE TITLE
Allow updatable field to be False

### ISSUE THREAD

**Issue by victorventuri** [ROVI-org/auto-soh#14]
I liked the idea of `updatable` being either `False` (to indicate a fully frozen `HealthVariable`) or a `tuple` of `str`s containing fields that can be modified. While we can use an empty `tuple` to indicate nothing can be updated, I feel like it's more intuitive to get a `False` when looking at that attribute.

**Comment by victorventuri** [comment]
Also, `updatable` needs to ordered, and not just a set, to assure all updates to internal variables are performed in the same order.

**Comment by WardLT** [comment]
I think this existing implementation already provides these abilities:
1. Clearing the set (`updatable.clear()`) is equivalent to setting it equal to False
2. Order is assured because it uses the order of fields in the class when outputting rather than the order in updatable 

Is that sufficient?

**Comment by victorventuri** [comment]
Yep, thanks!
