### ISSUE TITLE
Expand unit tests for HealthVariable

### ISSUE THREAD

**Issue by victorventuri** [ROVI-org/auto-soh#18]
We need to make sure we can update HealthVariables properly, including cases where:

1. they only have `float` fields
2. they only have `np.ndarray` fields
3. they only have `HealthVariable` fields
3.1. all `HealthVariable` fields are fully updatable
3.2. all  `HealthVariable` fields are fully un-updatable
3.3. all  `HealthVariable` fields are mixed of updatable and non-updatable fields
3.4. any combination of these 
4. they have any combination of `float`, `np.ndarray`, and fully updatable, fully non-updatable, and mixed `HealthVariable`s

**Comment by WardLT** [comment]
@victorventuri Is this still necessary?
