### ISSUE TITLE
ECM Joint UKF is very slow

### ISSUE THREAD

**Issue by victorventuri** [ROVI-org/auto-soh#36]
When running and testing the Joint UKF with an ECM, it appears the performance of the online estimator is very poor. Because of that, the unit test for it is marked as `slow` for pytest to skip it. The main two hypothesis on why this is happening are:
1. the states are provided to the model one-by-one, and therefore don't take advantage of, for example `numpy`'s efficient matrix multiplications
2. pydantic validations are slowing down performance, as filter-related objects need to be converted to model-related objects in the interface. 

Once this situation is fixed, the unit test `slow` marking should be removed.

**Comment by WardLT** [comment]
Fixed in #40 , the test runs every time as of #42
