### ISSUE TITLE
Implement Time-Varying Control States

### ISSUE THREAD

**Issue by WardLT** [ROVI-org/auto-soh#4]
For when our measurements between the outputs of a process are far apart and we know how the system was controlled in between 

Relevant after #3 is merged

**Comment by victorventuri** [comment]
Addressed in [6451f41](https://github.com/ROVI-org/auto-soh/commit/6451f416c91f5b2fdbc470f098167002d3b949e9), can now assume current behaves in linear fashion between inputs on ECM.
