### ISSUE TITLE
JointUKF Demo notebook is broken

### ISSUE THREAD

**Issue by victorventuri** [ROVI-org/auto-soh#54]
@WardLT When co-simulating, we get `AttributeError: 'DeltaDistribution' object has no attribute 'to_numpy'` from `moirae/estimators/online/__init__.py:270, in OnlineEstimator.step(self, u, y)`. I believe somewhere we were expecting something to be passed as an model-specific object, but got it already converted to estimator-specific object instead.

**Comment by WardLT** [comment]
Correct. The new `step` function (as of #50) takes InputQuantities rather than distributions. Feel free to change it back if you prefer

**Comment by victorventuri** [comment]
Fixed by https://github.com/ROVI-org/auto-soh/commit/f2af3a242555443b648d3628e2a8d3093afe55b0
