### ISSUE TITLE
[FEATURE] Save full estimation in BatteryDataToolkit form

### ISSUE THREAD

**Issue by victorventuri** [ROVI-org/auto-soh#83]
**Is your feature request related to a problem? Please describe.**
In the interface with BatteryDataToolkit, we don't store the full estimates of parameters. For example, when using `JointEstimator`s, we do not keep the full covariance matrix when saving to hdf5. Similarly, we store the mean of the estimations in the "raw_data", even though they correspond to a layer of processing on top of raw data. 

**Describe the solution you'd like**
It would be fantastic to be able to store the `MultivariateRandomDistribution` objects directly. At a minimum, it would be good to have the ability of storing the full covariance matrices as an additional entry in the Toolkit hdf5 file. 

**Describe alternatives you've considered**
The options we have discussed were:
1. Store in "raw_data", even though estimations are not raw data
2. Store in the "cycle_stats", which is a good idea, but we end up with cycle-average estimations, instead of fully-online estimation
3. Create a new dataframe to store the full estimates at each timestep of the raw data
4. Convert the `MultivariateRandomDistribution` to something else (json, pickle, etc.) and add it to the hdf5

**Additional context**
We want to avoid changing thing in the BatteryDataToolkit side, so it's best if this was done completely on the moirae side

**Comment by WardLT** [comment]
Fixed in #91
