### ISSUE TITLE
Validator for updatable parameters

### ISSUE THREAD

**Issue by victorventuri** [ROVI-org/auto-soh#9]
Based on recent progress on the ecm_redefine branch, I am shaping our approach to be "have an attribute that defines which other attributes can be updated by an external model". I have implemented that on the base HealthVariable class, but I believe we should have some form of validator to make sure these parameters are indeed updatable (and not, for example, strings, but they should all be numbers or iterables of numbers...)

**Comment by WardLT** [comment]
This is definitely fixed or out-dated.
