### ISSUE TITLE
[BUG] Issue with batching

### ISSUE THREAD

**Issue by victorventuri** [ROVI-org/auto-soh#95]
**Describe the bug**
When using batching for `SOCInterpolatedHealth` objects that are batched, the `get_value` method returns incomplete results.

**To Reproduce**
1. Create an ECM A-SOH with batched `R0`
```python
from moirae.models.ecm.advancedSOH import ECMASOH
asoh = ECMASOH.provide_template(has_C0=False, num_RC=0, R0 = [[1,2,3], [4,5,6]])
assert asoh.r0.batch_size == 2
```
2. Try to get values of at SOC of 0. (which should be an array similar to `[1., 4.]`) and at 0.5 (which should be an array similar to `[2., 5.]`)
```python
r0_vals = asoh.r0.get_value(soc=[0., 0.5])
```
4. Instead, we end up with `array([1., 5.])`

**Expected behavior**
When the `SOCInterpolatedHealth` object is batched, we expect the `get_value(soc=soc_1darray)` method to return an array of shape `(batch_size, len(soc_1darray))`

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.6.1
 - Version [e.g. 0.0.1]

Tagging @WardLT for discussion.

**Comment by WardLT** [comment]
Part of the problem here is ambiguity of 1D arrays. The current implementation gives you is the value at 0 for the first batch member, and the value at 0.5 for the second batch member. When making a fix, either eliminate support for 1D arrays (my preference) or make it super clear how a 1D array should be interpreted

**Comment by victorventuri** [comment]
Looking back at the code, I believe our reasoning was that the SOC, if batched, must match the size of the `SOCInterpolatedHealth` batch. If they have different batch sizes, we would need to return a 3D array.

**Comment by WardLT** [comment]
Let's hope we don't have a case with different batch sizes.

**Comment by victorventuri** [comment]
Solve by https://github.com/ROVI-org/auto-soh/pull/96
